name: Price Watcher

on:
  schedule:
    - cron: '40 1 * * *'  # 22:27 UTC = 01:27 МСК (UTC+3)
  workflow_dispatch:       # можно запустить вручную из GitHub UI

jobs:
  check-prices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests

      - name: Run price checker
        env:
          NTFY_TOPIC: parcing
        run: |
          python -c "
import os
token = 'y0__xCdoeLYBRjblgMgtZWKihWiDf1au7jJtVsy4bQO-a5A7-NMJA'
with open('watcher.py', 'r', encoding='utf-8') as f:
    code = f.read()
code = code.replace('YANDEX_DISK_TOKEN = \"YOUR_OAUTH_TOKEN_HERE\"', f'YANDEX_DISK_TOKEN = \"{token}\"')
with open('watcher_fixed.py', 'w', encoding='utf-8') as f:
    f.write(code)
          "
          python watcher_fixed.py
