name: Price Watcher

on:
  schedule:
    - cron: '0 2 * * *'  # 01:27 МСК (UTC+3 = 22:27 UTC)
  workflow_dispatch:

jobs:
  check-prices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests

      - name: Run price checker
        env:
          YANDEX_DISK_TOKEN: "y0__xCdoeLYBRjblgMgtZWKihWiDf1au7jJtVsy4bQO-a5A7-NMJA"
          NTFY_TOPIC: "parcing"
        run: python watcher.py
